### ISSUE TITLE
Invalid scope

### ISSUE THREAD

**Issue by robgarrett** [Rambalac/AmazonCloudDriveApi#10]
Not sure if something changed recently, but according to ACD API authentication is via Amazon Login. Unfortunately, the ACD scope values do not appear to work with Amazon Login.

Of course, I could be missing something. I have an ACD account, registered my App with https://login.amazon.com, and am using my client ID and secret in your latest code branch.

Help is appreciated.

**Comment by Rambalac** [comment]
Did you whitelisted your app for cloud drive?

**Comment by robgarrett** [comment]
Hmm, I didn't see where to do that. I logged in to https://login.amazon.com and went to the console. Is there somewhere I should look?

Thanks

R

**Comment by Rambalac** [comment]
Here developer.amazon.com/cd/sp/overview.html

**Comment by robgarrett** [comment]
Awesome, I'll try it tomorrow
Thanks

R
