### ISSUE TITLE
Cache clogging

### ISSUE THREAD

**Issue by topherhead** [Rambalac/AmazonCloudDriveApi#13]
It seems to clog on files that make it into the upload cache but never get uploaded.

**Comment by Rambalac** [comment]
Can you check if file never get uploaded but really already present in Amazon Cloud Drive Web client?
I found that some big files are reported by Amazon as failed to upload but really get uploaded and repeating upload fail because of conflict.

**Comment by topherhead** [comment]
I'm not sure.  I wrote a script that waits a while then clears the cache directory (and small files, is there a way to disable that?)  after each folder, I want to wait for it to finish running before I do any more testing.

Is there some limitation preventing it from writing directly to ACD?  Honestly I REALLY don't want a cache directory at all.  I would much rather it be a copy operation at the speed of my internet connection rather than caching and doing it in the background, it causes issues for large transfers.

**Comment by Rambalac** [comment]
Yes, cache is required.
For applications Windows drive is accessible for writing in random locations there is no garanty applications will not update something behind before closing it. There is no way on driver level to understand that application will write only contiguously. Files has to be uploaded to Amazon whole in one Http post, they can not be updated partially.
Also slow web upload speed can be treated by apps as timeout error and fail too.
