### ISSUE TITLE
Ambiguous Methods

### ISSUE THREAD

**Issue by ivanclay** [Rambalac/AmazonCloudDriveApi#14]
This method below, when I try run package throws error

```
 /// <summary>
        /// Returns object as parsed JSON from response.
        /// </summary>
        /// <typeparam name="T">Type of object to parse</typeparam>
        /// <param name="response">Response to parse</param>
        /// <returns>Parsed object</returns>
public static async Task<T> ReadAsAsync<T>(this HttpWebResponse response)
{
     var text = await response.ReadAsStringAsync().ConfigureAwait(false);
     return JsonConvert.DeserializeObject<T>(text);
}
```

**CS0121**	The call is ambiguous between the following methods or properties: 'Azi.Tools.HttpWebRequestExtensions.ReadAsStringAsync(System.Net.HttpWebResponse)' and 'Azi.Tools.HttpWebRequestExtensions.ReadAsStringAsync(System.Net.HttpWebResponse)'	AmazonCloudDriveApi

How to fix it?

**Comment by Rambalac** [comment]
There is only one ReadAsStringAsync. Two different references of library?

**Comment by ivanclay** [comment]
I realized there was only one method . I was running in circles trying to solve, but I did not succeed . Do you have any idea what might be going on?

**Comment by Rambalac** [comment]
I have seen that only when the same class was referenced from two different libraries.
