### ISSUE TITLE
Files uploading not stuck

### ISSUE THREAD

**Issue by ozone1979** [Rambalac/AmazonCloudDriveApi#15]
I'm noticing that Files uploading is stuck at 35.
and in %TEMP%\ACDDokanNetCache\Uploads, I see the file pairs still there.

How do I resume the uploads?

**Comment by exilewolf** [comment]
same issue being seen  but at 107

**Comment by ozone1979** [comment]
What I've seen so far is that I can mount and then unmount, and the uploads finish.  However, I am seeing that the Small Files cache can hold at times,  but I manually go and delete those when I want them gone.  The Settings GUI doesn't allow me to clear the Small Files cache though.

**Comment by Rambalac** [comment]
Is it about library or Amazon Cloud Drive disk app? 
If it'is about app it's here https://github.com/Rambalac/ACDDokanNet and it because you created issue here it's "a bit" outdated. Now it should work.
