### ISSUE TITLE
Will not work with latest Dokan.NET 1.0

### ISSUE THREAD

**Issue by exilewolf** [Rambalac/AmazonCloudDriveApi#17]
So I tried to do the install with Doken.NET redist 1 and the installer tells me its not installed. ?

**Comment by Rambalac** [comment]
Is it about library or Amazon Cloud Drive disk app? 
If it'is about app it's here https://github.com/Rambalac/ACDDokanNet and it because you created issue here it's "a bit" outdated. Latest can use Dokan 1.0.0
