### ISSUE TITLE
Using Robo Copy 

### ISSUE THREAD

**Issue by exilewolf** [Rambalac/AmazonCloudDriveApi#19]
When using robopy copy with ACD It appears to remove the remove directory from the cloud when using Robocopy <dir> <dir>  regardless of switches.

**Comment by Rambalac** [comment]
Is it about library or Amazon Cloud Drive disk app? 
If it'is about app it's here https://github.com/Rambalac/ACDDokanNet and it because you created issue here it's "a bit" outdated.
