### ISSUE TITLE
Get Customer/Profile details

### ISSUE THREAD

**Issue by Kyrodan** [Rambalac/AmazonCloudDriveApi#20]
I need to get the profile (= the Amazon Customer) for an Amazon Drive Account - especially Name and ID.
This can be retrieved when getting an AccessToken (providing additional scopes).
See details here: https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/customer_profile.html and https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/obtain_customer_profile.html

**Comment by Rambalac** [comment]
Thanks. I was a bit busy. Do you know good add-on to deploy to nuget? Add-on I used cannot be installed on new PC with new VS

**Comment by Kyrodan** [comment]
Maybe VS-Built-In-Nuget (Command Line)? 
Commands:
* pack 
* deploy

See https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference for details.

A sample how I dor it in my own library: https://github.com/Kyrodan/hidrive-dotnet-sdk/blob/master/build.cmd

**Comment by Rambalac** [comment]
By the way, I found an easier way with Appveyor. Just put nuspec into lib project for metadata and Appveyor will do everything.
