### ISSUE TITLE
Using cygwin copy "cp", i get "File too large"

### ISSUE THREAD

**Issue by swvajanyatek** [Rambalac/AmazonCloudDriveApi#24]
I'm not sure if its the same problem, but when using Beyond Compare the file appears to copy to the mounted ACD folder, but then disappear immediately after the copying completes

**Comment by Rambalac** [comment]
Is it about library or Amazon Cloud Drive disk app? 
If it'is about app it's here https://github.com/Rambalac/ACDDokanNet and it because you created issue here it's "a bit" outdated. Do you have it in new version?
