### ISSUE TITLE
Temp-dir not found

### ISSUE THREAD

**Issue by michal78** [Rambalac/AmazonCloudDriveApi#28]
I get this error when trying to mount my drive. I even tried with administrator rights.
It translates to "[TEMP PATH][FILE] not found!"
What should i be looking for in the logs ?
![2016-11-20 18_21_16-programs](https://cloud.githubusercontent.com/assets/239061/20464781/59e875f8-af4e-11e6-8642-389bd156509a.png)

**Comment by Rambalac** [comment]
Issue is not related to this project
