### ISSUE TITLE
System.Net.ConnectStreap.position is not supported

### ISSUE THREAD

**Issue by denisvmedia** [Rambalac/AmazonCloudDriveApi#6]
Here: Azi.Tools.HttpClient::GetToStreamAsync() there is a problem. It is not possible to pass a progress function, since it immediately leads to an exception, because position field is not supported. Also, there is an apparent typo (red instead of read).

**Comment by denisvmedia** [comment]
I think, instead of position we should accumulate data from the _read_ ("red") variable.

**Comment by Rambalac** [comment]
Just pushed fix and unit test.

**Comment by denisvmedia** [comment]
It works. Thank you.
