### ISSUE TITLE
We need a way to break the download process

### ISSUE THREAD

**Issue by denisvmedia** [Rambalac/AmazonCloudDriveApi#7]
Currently, there is no way to break the download process. Maybe instead of nextProgress should be checked for being set to -1. Somehow this way:

    while ((read = await input.ReadAsync(buff, 0, buff.Length).ConfigureAwait(false)) > 0)
    {
        await stream.WriteAsync(buff, 0, read).ConfigureAwait(false);
        totalRead += read;
        if (progress != null && totalRead >= nextProgress)
        {
            nextProgress = progress.Invoke(totalRead);
            if (nextProgress == -1) // passing -1 from the progress function, will allow us breaking the download
            {
                break;
            }
        }
    }

**Comment by Rambalac** [comment]
I was thinking to throw OperationCanceledException for that.

**Comment by denisvmedia** [comment]
Well, but how would it work from the site of the application? Still passing nextProgress == -1? BTW, I changed that locally to what I proposed, and it works properly for me, no issues.

**Comment by Rambalac** [comment]
I just pushed Unit test that demonstrates that. Download throws OperationCancelledException.

**Comment by denisvmedia** [comment]
Thank you for your example. However, I'm still in doubt how to catch this exception in the code like here: https://github.com/denisvmedia/farnet-acd/blob/master/ACDClient.cs#L166 (where instead of returning -1 I would throw OperationCancelledException according to your proposal). Try-catch around await call doesn't work for me :(

P.S. Please take into account that I'm not a c# pro, and this might be trivial question, but I'd be thankful for your help anyway.

**Comment by Rambalac** [comment]
It's just
```
try {
    await Amazon.Files.Download(testFile.id, memStr, bufferSize: 10, progress: ProgressCancel);
} catch(OperationCanceledException)
{

}
```

While is not short as -1 way it allows to understand when operation is really canceled. And IMHO you still need try catch in case of other problems.

**Comment by denisvmedia** [comment]
I don't know why didn't work before, but now it works for me. Thanks for your help :)
